version: '3.7'

services:
  my_prod_postgres:
    image: postgres
    container_name: my_prod_postgres
    volumes:
      - my_prod_volume:/var/lib/postgresql/data
      - /home/pythonuser/muhammed/data:/data
    command: "psql -U {MY_PROD_USER} -d {MY_PROD_DB} -f /data/mydump.sql"
    env_file:
      - ./.env_db
    expose:
      - 6543:5432

  my_django:
    image: personalwebsite:v1
    build:
      context: .
      dockerfile: Dockerfile_prod
    volumes:
      - /home/pythonuser/muhammed/muhammedbuyukkinaci.com/staticfiles:/app/staticfiles
      - /home/pythonuser/muhammed/muhammedbuyukkinaci.com/media:/app/media
    container_name: my_django
    depends_on:
      - my_prod_postgres
    restart: always
    env_file:
      - ./.env
    ports:
    - 8000:8000

volumes:
  my_prod_volume:
    external: true
