version: '3.7'

services:
  my_django:
    image: personalwebsite:v1
    build: 
      context: .
      dockerfile: Dockerfile_dev
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    container_name: my_django
    env_file:
      - ./.env
    expose:
    - 8000

  my_nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile_dev
    image: nginx_image:latest
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    container_name: my_nginx
    ports:
      - 80:80
    depends_on:
      - my_django

volumes:
  static_volume:
    external: true
  media_volume:
    external: true
