version: '3.7'

services:
  my_django:
    image: personalwebsite:v1
    build:
      context: .
      dockerfile: Dockerfile_prod
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    container_name: my_django
    env_file:
      - ./.env
    expose:
    - 8000

  my_nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile_prod
    image: nginx_image
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - /home/pythonuser/certbot/www:/var/www/certbot/:ro
      - /home/pythonuser/nginx/conf/:/etc/nginx/conf.d/:ro  
    container_name: my_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - my_django
      
  my_certbot:
    image: certbot/certbot:latest
    volumes:
      - /home/pythonuser/certbot/www/:/var/www/certbot/:rw
      - /home/pythonuser/certbot/conf/:/etc/letsencrypt/:rw
    container_name: my_certbot
    depends_on:
      - my_nginx
volumes:
  static_volume:
    external: true
  media_volume:
    external: true
  