version: '3.7'

services:
  my_django:
    image: personalwebsite:v1
    build:
      context: .
      dockerfile: Dockerfile_prod
    volumes:
      - /home/pythonuser/staticfiles:/app/staticfiles
      - /home/pythonuser/media:/app/media
    container_name: my_django
    env_file:
      - ./.env
    ports:
    - 8000:8000

  # my_nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile_prod
  #   image: nginx_image:latest
  #   volumes:
  #     - static_volume:/app/staticfiles
  #     - media_volume:/app/media
  #     # - /home/pythonuser/certbot/www:/var/www/certbot/:ro
  #     # - /home/pythonuser/nginx/conf/:/etc/nginx/conf.d/:ro  
  #   container_name: my_nginx
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - my_django
      
  # my_certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - /home/pythonuser/certbot/www/:/var/www/certbot/:rw
  #     - /home/pythonuser/certbot/conf/:/etc/letsencrypt/:rw
  #   container_name: my_certbot
#volumes:
#   static_volume:
#     external: true
  # media_volume:
  #   external: true
