# Generated by Django 3.2 on 2021-05-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_skills_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_link', models.CharField(max_length=100)),
                ('page_fontawesomeclass', models.CharField(max_length=50)),
                ('page_category', models.CharField(choices=[('socialmedia', 'socialmedia'), ('business', 'business')], default='socialmedia', max_length=20)),
            ],
        ),
    ]
