# Generated by Django 3.2 on 2021-05-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_color',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
