# Generated by Django 3.2 on 2021-05-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_page_page_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
