# Generated by Django 3.2 on 2021-09-01 18:42

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_image_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=sorl.thumbnail.fields.ImageField(upload_to='images/'),
        ),
    ]
