# Generated by Django 3.2 on 2021-09-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_alter_image_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
