# Generated by Django 3.2 on 2021-09-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_alter_image_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='filename',
            new_name='image',
        ),
    ]
