# Generated by Django 3.2 on 2021-08-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
