# Generated by Django 3.2 on 2021-08-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210824_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
