# Generated by Django 3.2 on 2021-08-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_owner',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
