# Generated by Django 3.2 on 2021-08-27 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_article_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
