# Generated by Django 3.2 on 2021-08-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_article_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_source',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
