# Generated by Django 3.2 on 2021-08-27 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_article_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_source',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
