# Generated by Django 3.2 on 2021-08-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_summary', models.CharField(max_length=50)),
                ('home_text', models.TextField(max_length=40)),
            ],
        ),
    ]
