# Generated by Django 3.2 on 2021-08-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='home_text',
            field=models.TextField(),
        ),
    ]
