# Generated by Django 3.2 on 2021-05-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_name', models.CharField(max_length=30)),
                ('testimonial_title', models.CharField(max_length=100)),
                ('testimonial_content', models.TextField()),
                ('testimonial_collapsed', models.BooleanField(default=True)),
                ('testimonial_number', models.CharField(max_length=20)),
            ],
        ),
    ]
