# Generated by Django 3.2 on 2021-05-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_number',
            field=models.CharField(max_length=30),
        ),
    ]
