# Generated by Django 3.2 on 2021-10-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_question', models.CharField(max_length=200)),
                ('quiz_answer1', models.CharField(max_length=50)),
                ('quiz_answer2', models.CharField(max_length=50)),
                ('quiz_answer3', models.CharField(max_length=50)),
                ('quiz_answer4', models.CharField(max_length=50)),
                ('quiz_correct_answer', models.CharField(max_length=50)),
            ],
        ),
    ]
